GET http://localhost:3000 HTTP/1.1
### delimitatori di richieste
GET http://localhost:3000/books HTTP/1.1
### delimitatori di richieste
GET http://localhost:3000/books/1 HTTP/1.1
### delimitatori di richieste
POST http://localhost:3000/books HTTP/1.1 
Content-Type: application/json

{
"title": "Don Quixote 3647384", 
 "author": "Miguel de Cervantes",
 "isbn": "9780060934347",
 "published_year":  1605
}
### delimitatori di richieste
PUT  http://localhost:3000/books/27 HTTP/1.1 
Content-Type: application/json

{
"title": "Don Quixote 13"
}
### delimitatori di richieste
delete http://localhost:3000/books/27 HTTP/1.1
### delimitatori di richieste
GET http://localhost:3000/books?authordName=Miguel de Cervantes&authordName=Dante Alighieri&publicationYear=1605&publicationYear=1851&orderBy=ASC&page=1&rowPage=10 HTTP/1.1